#	Makefile for the PinMonitor example
#
#	The Makefile is using the Arduino-Makefile by sudar.
#	See https://github.com/sudar/Arduino-Makefile for details.
#
#	Check the arduino-env file in this directory for the environment variables
#	that need to be defined.

BOARD_TAG = nano328
MONITOR_PORT = /dev/ttyUSB0

USER_LIB_PATH = ./lib

LOCAL_INO_SRCS += src/PinMonitor.ino

include $(ARDUINO_MK)

